title: TaeWoo Kim - Programmer
description: > # this means to ignore newlines until "baseurl:"
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: TaeWoo Kim # add your name
author-img: my-pic.jpg # add your photo
about-author: Software Developer # add description
twitter: # add your Twitter handle
facebook: taewoo.kim.9400 # add your Facebook handle
github: lioliolio # add your Github handle
linkedin: # add your Linkedin handle
email: kpc00100@gmail.com # add your Email address

# Disqus
discus-identifier: lioliolio # add your discus identifier

# Tracker
analytics: UA-113862957-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
